name: archer-ld
channels:
    - conda-forge
    - defaults
    - bioconda
dependencies:
    - python>=3.9
    - cupy
    - scipy
    - zarr
    - openmpi
    - kerchunk
    - cyvcf2
    - pip
    - pip:
        - zarrs
        - mpi4py
        - bio2zarr